/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/derek.glb
*/

import React, { useContext, useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

import { StoreContext } from '../../../context/store'

function Derek(props) {
  const group = useRef(null)
  const { nodes, materials, animations } = useGLTF('/models/derek.glb')
  const { actions, mixer } = useAnimations(animations, group)
  const { value } = useContext(StoreContext)

  useEffect(() => {
    mixer.timeScale = 0.12
  }, [])

  useEffect(() => {
    if (!value.modelLoading) {
      actions.ArmatureAction[value.about_me.play_audio ? 'play' : 'stop']?.()
    }
  }, [value.about_me.play_audio, value.modelLoading])

  return (
    <group ref={group} {...props} dispose={null} position={[0, 0, 0]}>
      <group name="Scene" scale={1}>
        <group name="Armature" position={[0, 0, 0]} scale={[1, 1, 1]}>
          <primitive object={nodes.head} />
          <group name="body">
            <skinnedMesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials.Head_base} skeleton={nodes.Cube002.skeleton} />
            <skinnedMesh name="Cube002_1" geometry={nodes.Cube002_1.geometry} material={materials.Hair_base} skeleton={nodes.Cube002_1.skeleton} />
            <skinnedMesh name="Cube002_2" geometry={nodes.Cube002_2.geometry} material={materials.gorro_base} skeleton={nodes.Cube002_2.skeleton} />
            <skinnedMesh name="Cube002_3" geometry={nodes.Cube002_3.geometry} material={materials['Shoes base']} skeleton={nodes.Cube002_3.skeleton} />
            <skinnedMesh name="Cube002_4" geometry={nodes.Cube002_4.geometry} material={materials['Sueter base']} skeleton={nodes.Cube002_4.skeleton} />
            <skinnedMesh name="Cube002_5" geometry={nodes.Cube002_5.geometry} material={materials['teef base b']} skeleton={nodes.Cube002_5.skeleton} />
            <skinnedMesh name="Cube002_6" geometry={nodes.Cube002_6.geometry} material={materials['teef t base']} skeleton={nodes.Cube002_6.skeleton} />
            <skinnedMesh name="Cube002_7" geometry={nodes.Cube002_7.geometry} material={materials.inside_mouth} skeleton={nodes.Cube002_7.skeleton} />
            <skinnedMesh name="Cube002_8" geometry={nodes.Cube002_8.geometry} material={materials['pestanas base']} skeleton={nodes.Cube002_8.skeleton} />
            <skinnedMesh name="Cube002_9" geometry={nodes.Cube002_9.geometry} material={materials.eye} skeleton={nodes.Cube002_9.skeleton} />
            <skinnedMesh name="Cube002_10" geometry={nodes.Cube002_10.geometry} material={materials['eye.001']} skeleton={nodes.Cube002_10.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/derek.glb')

export default Derek
